# Generated by Django 4.1.1 on 2022-10-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
